server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  type-aliases-package: com.liupan.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #集群注册地址
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #单机版注册地址
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8001  #自定义服务名称
    prefer-ip-address: true   #访问路径可以显示IP地址
    #eureka向服务端发送心跳的时间间隔，单位为秒（默认３０秒）
    lease-renewal-interval-in-seconds: １
    #eureka服务端在最后一次接收到心跳后等待时间上限，单位为秒（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds:  2